apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: os-suse-chost
spec:
  deployment:
    extension:
      helm:
        ociRepository:
          ref: europe-docker.pkg.dev/gardener-project/public/charts/gardener/extensions/os-suse-chost:v1.35.0
  resources:
  - kind: OperatingSystemConfig
    type: suse-chost
