image:
  repository: eu.gcr.io/gardener-project/gardener/extensions/os-suse-chost
  tag: latest
  pullPolicy: IfNotPresent

resources: {}

vpa:
  enabled: true
  resourcePolicy:
    minAllowed:
      cpu: 50m
      memory: 64Mi
  updatePolicy:
    updateMode: "Auto"

controllers:
  concurrentSyncs: 5
  ignoreOperationAnnotation: false

leaderElection:
  resourceLock: leases

disableControllers: []

gardener:
  version: ""
