apiVersion: v1
kind: Service
metadata:
  name: gardener-extension-os-suse-chost
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.resources.gardener.cloud/from-policy-pod-label-selector: all-seed-scrape-targets
    networking.resources.gardener.cloud/from-policy-allowed-ports: '[{"port":{{ .Values.metrics.port }},"protocol":"TCP"}]'
    networking.resources.gardener.cloud/namespace-selectors: '[{"matchLabels":{"kubernetes.io/metadata.name":"garden"}}]'
    networking.resources.gardener.cloud/pod-label-selector-namespace-alias: extensions
  labels:
    app.kubernetes.io/name: gardener-extension-os-suse-chost
    helm.sh/chart: gardener-extension-os-suse-chost
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gardener-extension-os-suse-chost
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    protocol: TCP
